### ISSUE TITLE
[BUG] Z-align, unknown command

### ISSUE THREAD

**Issue by Zazou49** [Dtcreation/Firmware-Molise-Artillery#93] opened 2021-09-07 06:43 UTC
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When I want to do a Z-align, I've an error : `Unknown command : G34`

![IMG_3660](https://user-images.githubusercontent.com/89610869/132296797-09101760-2902-4948-8f51-e4d3559294b2.JPG)

### Version of Marlin Firmware

Molise 2.3 (Marlin 2.0.9.1)

### Printer model

Artillery Genius

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by Zazou49** [comment] 2021-09-07 14:30
As I can see in your video, it disable be default.

Can you share your configuration.h file for Genius stock with BL Touch ? I'll try to compile myself !

Thank you again

**Comment by SgtWest10** [comment] 2021-09-07 20:17
Maybe it's not a but.
Can i help you ?

**Comment by SgtWest10** [comment] 2021-09-07 20:24
@Zazou49
Maybe it's not a bug.
Can i help you ?

**Comment by Zazou49** [comment] 2021-09-07 20:28
I compiled myself the firmware with Z Auto Align enable and it seems working !

**Comment by SgtWest10** [comment] 2021-09-07 20:32
@Zazou49
be carefull, you need to remove the belt from the Z axes.

**Comment by Zazou49** [comment] 2021-09-07 20:34
Yes, I removed the belt before the Z align !

**Comment by SgtWest10** [comment] 2021-09-07 20:37
What do you want to know about to compile yourself ?

**Comment by Zazou49** [comment] 2021-09-07 20:38
I was afraid to enable / disable some options, but it was relatively easy with the video.

**Comment by SgtWest10** [comment] 2021-09-07 20:54
Use visual studio code and platformio extension.
You edit the file Marlin\configuration.adv, uncomment your hardware configuration in line 87 to 182.
You edit the file platformio.ini, the line 16 "default_envs = change_value", replace "change_value" with your board.
For your board value, it's in line 108 to 117, in file Marlin\configuration.adv.
Finally build the firmaware.
If you don't have error during compile, it's Okay.

**Comment by SgtWest10** [comment] 2021-09-07 21:13
@Zazou49 
if you have an original screen, I advise you to change the connection on the board to the exp1 port. this will avoid opening the printer to flash the firmware, using the disconnected button in the screen menu.

**Comment by Zazou49** [comment] 2021-09-07 21:14
Yes stock srceen, Open the printer is not needed, just click on "disconnect" on the screen and I can flash.

**Comment by SgtWest10** [comment] 2021-09-07 21:15
thank you for your work
@Dtcreation

**Comment by SgtWest10** [comment] 2021-09-07 21:18
@Zazou49 
Okay. Good.
On my sidewinder x1, I made the modification to make it work !

**Comment by JRRN** [comment] 2021-11-06 10:48
@Zazou49 if it is resolved, close the issue, please!

**Closed** 2022-01-08 14:13 UTC
